sudo: requied
services:
  - docker

before_install:
  - docker build -t superauman/docker-react -f Dockerfile.dev .

script:
  - docker run superauman/docker-react npm run test -- --coverage

deploy :
  provider : elasticbeanstalk
  region : "ap-southeast-1"
  app : "Docker-React"
  env : "DockerReact-env"
  bucket_name : "elasticbeanstalk-ap-southeast-1-253424059284"
  bucket_path : "docker"
  on:
    branch : master
  access_key_id : "$AWS_ACCESS_KEY"
  secret_access_key :
      secure : "$AWS_SECRET_KEY"